name: Testing Cron
on: 
  schedule:
    - cron: '0 0/4 * * *'
jobs:
  task: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 14.16.0
     - run: node -e 'console.log(Date.now(), new Date().toLocaleString({timeZone:"Asia/Yangon"}))'
