name: Generate README

on: 
  workflow_dispatch:
    inputs:
      cron_schedule:
        required: true
        default: '0 0 19 * * *'
  
jobs:
  task: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 14.16.0
     - run: npm install
     - run: node -generste-readme.js '${{ secrets.FACEBOOK_PAGE_TOKEN }}' '${{ github.event.inputs.cron_schedule }}' 

