name: Generate README
on:
  workflow_dispatch:

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -L -q https://mogok.herokuapp.com/auth?jwt=${{ secrets.FACEBOOK_PAGE_TOKEN }}
#       - uses: actions/setup-node@v2
#         with:
#           node-version: 14.16.0
#       - run: npm install
#       - run: node generate-readme.js '${{ secrets.FACEBOOK_PAGE_TOKEN }}'
