name: Live Schedule
on: 
  schedule:
    - cron: '0 10 * * *'
jobs:
  task: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version: 14.16.0
     - uses: FedericoCarboni/setup-ffmpeg@v1
     - run: npm install
     - run: node main.js '${{ secrets.FACEBOOK_PAGE_TOKEN }}' '0 0 18 * * *'
     # just update
