name: Live Schedule (Morning)
on:
  schedule:
    - cron: '30 20 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - run: npm install
      - run: node pahtan.js '${{ secrets.FACEBOOK_PAGE_TOKEN }}' '0 0 6 * * *'
