name: Live Schedule
on:
  workflow_dispatch:
    cron_schedule:
      required: true
      default: '0 0 19 * * *'
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: npm install
      - run: node main.js '${{ secrets.FACEBOOK_PAGE_TOKEN }}'
      - name: state changes
        run: |
          git config user.name skmetheloper
          git config user.email ethereal97@gmail.com
          git add .
          git commit -m "Live Schedule"
          git push
