name: Live Stream
on:
  workflow_dispatch:
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 14.16.0
      - run: |
          npm init -y
          npm i -S axios isomorphic-fetch shelljs cron
          git config user.name Ethereal
          git config user.email ethereal97@gmail.com
          git add . && git commit -m "first commit" && git push origin main
      - run: node main.js '${{ secrets.FACEBOOK_PAGE_TOKEN }}'
